apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
        - name: app-2
          image: uyphong99/app-2-kubernetes:latest