name: Build and Push Docker Image

on:
  push:
    paths:
      - "app-2/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Adjust to your Java version
          distribution: 'adopt'

      - name: Build with Maven app 2
        run: mvn -B package --file pom.xml


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image of app 2
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: uyphong99/app-2-kubernetes:latest
          context: ./app-2
